main: me.devnatan.lobbyqueue.LobbyQueue
name: LobbyQueue
version: 2.0
author: DevNatan
softdepend: [PlaceholderAPI]
website: https://github.com/DevNatan
description: Copyright (c) 2018 DevNatan. Todos os direitos reservados.