main: me.devnatan.lobbyqueue.LobbyQueue
name: LobbyQueue
version: 3.0
author: DevNatan
website: https://github.com/DevNatan
description: Copyright (c) 2018 DevNatan. Todos os direitos reservados.

commands:
  testqueue:
    description: Testar a fila.